version: "3.7"
services:
  page:
    image: dmsfourteam/builder
    build: ./app
    ports:
      - 80:3000
    # volumes:
      # - ./html:/app/release
  # web:
  #   image: nginx:latest
  #   depends_on: 
  #     - "builder"
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./html/build:/usr/share/nginx/html
  #     - ./nginx/conf.d:/etc/nginx/conf.d
